"""Canonical object names for the latest five-CR5A CoppeliaSim scene.

The contract is generated by the Lua scripts in ``scenes/``. Imported CR5A
models keep their roots at ``/R1`` ... ``/R5`` while cell fixtures, parts and
targets live below ``/FiveCR5A_Cell``.
"""

from __future__ import annotations


SCENE_ROOT = "/FiveCR5A_Cell"
SCENE_FILE = "compact_cell1ttt.ttt"
ROBOT_IDS = ("R1", "R2", "R3", "R4", "R5")
ARM_JOINT_ALIASES = tuple(f"joint{index}" for index in range(1, 7))

ROBOT_ROOTS = {robot_id: f"/{robot_id}" for robot_id in ROBOT_IDS}
ROBOT_BASES = {
    robot_id: f"{SCENE_ROOT}/RobotBases/{robot_id}_Base"
    for robot_id in ROBOT_IDS
}
ROBOT_TIPS = {
    "R1": "R1_gripper_tip",
    "R2": "R2_vacuum_tip",
    "R3": "R3_gripper_tip",
    "R4": "R4_tool_tip",
    "R5": "R5_gripper_tip",
}
ROBOT_TOOL_ROOTS = {
    robot_id: f"/{robot_id}/{robot_id}T" for robot_id in ROBOT_IDS
}

TARGET_GROUPS = {
    "R1": "R1_Targets",
    "R2": "R2_Targets",
    "R3": "R3_Targets",
    "R4": "R4_Targets",
    "R5": "R5_Targets",
    "CAMERA": "Sensor_Targets",
}
ROBOT_TARGET_NAMES = {
    "R1": (
        "R1_HOME_REF",
        "R1_BOX_PICK_APP",
        "R1_BOX_PICK_TCP",
        "R1_BOX_PLACE_APP",
        "R1_BOX_PLACE_TCP",
        "R1_TERMINAL_PICK_APP",
        "R1_TERMINAL_PICK_TCP",
        "R1_TERMINAL_PLACE_APP",
        "R1_TERMINAL_PLACE_TCP",
    ),
    "R2": (
        "R2_HOME_REF",
        "R2_PCB_PICK_APP",
        "R2_PCB_PICK_TCP",
        "R2_PCB_PLACE_APP",
        "R2_PCB_PLACE_TCP",
    ),
    "R3": (
        "R3_HOME_REF",
        "R3_MODULE_PICK_APP",
        "R3_MODULE_PICK_TCP",
        "R3_MODULE_PLACE_APP",
        "R3_MODULE_PLACE_TCP",
        "R3_PRODUCT_PICK_APP",
        "R3_PRODUCT_PICK_TCP",
        "R3_PRODUCT_PLACE_INSPECTION_APP",
        "R3_PRODUCT_PLACE_INSPECTION_TCP",
    ),
    "R4": (
        "R4_HOME_REF",
        "R4_SCREW_APP",
        "R4_SCREW_TCP",
        "R4_SCREW_PRESS",
    ),
    "R5": (
        "R5_HOME_REF",
        "R5_PRODUCT_PICK_APP",
        "R5_PRODUCT_PICK_TCP",
        "R5_GOOD_PLACE_APP",
        "R5_GOOD_PLACE_TCP",
        "R5_DEFECT_PLACE_APP",
        "R5_DEFECT_PLACE_TCP",
    ),
    "CAMERA": ("CAMERA_INSPECTION_CENTER",),
}


def _build_target_paths() -> dict[str, str]:
    paths: dict[str, str] = {}
    for resource_id, target_names in ROBOT_TARGET_NAMES.items():
        group = TARGET_GROUPS[resource_id]
        for target_name in target_names:
            paths[target_name] = (
                f"{SCENE_ROOT}/Targets/{group}/{target_name}"
            )
    return paths


POINTS = _build_target_paths()
HOME_POINTS = {
    robot_id: POINTS[f"{robot_id}_HOME_REF"] for robot_id in ROBOT_IDS
}

PARTS = {
    "BOX_BLANK": f"{SCENE_ROOT}/Parts/Box_Blank",
    "PCB_SUPPLY": f"{SCENE_ROOT}/Parts/PCB_Supply",
    "CONTROL_MODULE_SUPPLY": f"{SCENE_ROOT}/Parts/Control_Module_Supply",
    "TERMINAL_BLOCK_SUPPLY": f"{SCENE_ROOT}/Parts/Terminal_Block_Supply",
    "ASSEMBLY_PRODUCT": f"{SCENE_ROOT}/Parts/Assembly_ControlBox_Product",
    "INSPECTION_PRODUCT": f"{SCENE_ROOT}/Parts/Inspection_ControlBox_Product",
}
AREAS = {
    "BOX_SUPPLY": f"{SCENE_ROOT}/Areas/Box_Supply_Area",
    "TERMINAL_SUPPLY": f"{SCENE_ROOT}/Areas/Terminal_Supply_Area",
    "PCB_SUPPLY": f"{SCENE_ROOT}/Areas/PCB_Supply_Area",
    "MODULE_SUPPLY": f"{SCENE_ROOT}/Areas/Module_Supply_Area",
    "ASSEMBLY": f"{SCENE_ROOT}/Areas/Assembly_Area",
    "ASSEMBLY_FIXTURE": f"{SCENE_ROOT}/Areas/Assembly_Fixture",
    "INSPECTION_SCREW": f"{SCENE_ROOT}/Areas/Inspection_Screw_Area",
    "INSPECTION_PLATFORM": f"{SCENE_ROOT}/Areas/Inspection_Platform",
}
CONVEYORS = {
    "GOOD": f"{SCENE_ROOT}/Conveyors/Good_Conveyor",
    "DEFECT": f"{SCENE_ROOT}/Conveyors/Defect_Conveyor",
}
SENSORS = {
    "FIXED_VISION_CAMERA": (
        f"{SCENE_ROOT}/Sensors/Fixed_Vision_Camera_Station"
    ),
}

# Scene-specific Cartesian safety envelopes used by the validated simulation
# trajectories.  These bounds belong to the exact scene fingerprint recorded
# in every R1-R5 plan; they are not hardware workspaces.
WORKSPACES = {
    "R1": {"lower": (-2.25, -0.20, 0.04), "upper": (-0.82, 1.18, 1.55)},
    "R1_PRIVATE_SUPPLY": {
        "lower": (-2.08, 0.00, 0.15),
        "upper": (-1.55, 0.55, 0.65),
        "lock_required": False,
    },
    # The imported R2 model occupies y=-0.8164 m in its initial clearance
    # posture.  Include that posture plus a small numerical guard margin.
    "R2": {"lower": (-1.90, -0.83, 0.04), "upper": (-0.95, 0.38, 1.55)},
    "R2_PRIVATE_SUPPLY": {
        "lower": (-1.46, -0.42, 0.14),
        "upper": (-1.10, -0.14, 0.55),
        "lock_required": False,
    },
    # The validated R3 product-pick clearance puts the left-most arm shape at
    # x=-1.4114 m.  Keep a small guard margin around that scene-native pose;
    # collision checking remains active for every replayed path segment.
    "R3": {"lower": (-1.42, -0.48, 0.04), "upper": (0.60, 0.76, 1.55)},
    "R3_PRIVATE_SUPPLY": {
        "lower": (-1.02, -0.20, 0.14),
        "upper": (-0.68, 0.10, 0.55),
        "lock_required": False,
    },
    "R4": {"lower": (-0.05, -0.20, 0.04), "upper": (1.00, 0.72, 1.55)},
    "R5": {"lower": (-0.68, -1.48, 0.04), "upper": (1.30, 0.48, 1.55)},
    "ASSEMBLY_SHARED": {
        "lower": (-1.43, -0.04, 0.20),
        "upper": (-0.84, 0.48, 0.68),
        "lock_required": True,
        "max_robots": 1,
    },
    "INSPECTION_SHARED": {
        "lower": (-0.55, -0.35, 0.20),
        "upper": (0.80, 0.65, 0.75),
        "lock_required": True,
        "max_robots": 1,
    },
}

ROS_TOPICS = {
    "GLOBAL_COMMAND": "/compact_cell/cmd",
    "MAIN_COMMAND": "/compact_cell/main_cmd",
    "TOOL_COMMAND": "/compact_cell/tool_cmd",
    "STATUS": "/compact_cell/status",
    "JOINT_COMMAND": "/compact_cell/joint_cmd",
    "JOINT_STATUS": "/compact_cell/joint_status",
    **{
        f"{robot_id}_COMMAND": f"/compact_cell/{robot_id.lower()}_cmd"
        for robot_id in ROBOT_IDS
    },
}

# Commands accepted by ROS2_CompactCell_Bridge_V3_ColorCycle.lua.
PROCESS_COMMANDS = {
    "RESET_CELL",
    "COLOR_NEXT",
    "COLOR_1",
    "COLOR_2",
    "COLOR_3",
    "SHOW_ASSEMBLY_SHELL",
    "SHOW_ASSEMBLY_PCB",
    "SHOW_ASSEMBLY_MODULE",
    "SHOW_ASSEMBLY_FULL",
    "SHOW_INSPECTION_FULL",
    "CAMERA_GOOD",
    "CAMERA_DEFECT",
    "CONVEYOR_GOOD",
    "CONVEYOR_DEFECT",
    "R1_BOX_PLACED",
    "R2_PCB_PLACED",
    "R3_MODULE_PLACED",
    "R1_TERMINAL_PLACED",
    "R3_PRODUCT_TO_INSPECTION",
    "R4_SCREW_DONE",
    "R5_SORT_GOOD_DONE",
    "R5_SORT_DEFECT_DONE",
}
QUALITY_COMMANDS = {"OK": "CAMERA_GOOD", "NG": "CAMERA_DEFECT"}
PROCESS_SIGNAL_UPDATES = {
    "RESET_CELL": ("cell_product_state", "reset"),
    "COLOR_NEXT": ("cell_product_state", "color_next"),
    "COLOR_1": ("cell_product_state", "color_1"),
    "COLOR_2": ("cell_product_state", "color_2"),
    "COLOR_3": ("cell_product_state", "color_3"),
    "SHOW_ASSEMBLY_SHELL": ("cell_product_state", "assembly_shell"),
    "SHOW_ASSEMBLY_PCB": ("cell_product_state", "assembly_pcb"),
    "SHOW_ASSEMBLY_MODULE": ("cell_product_state", "assembly_module"),
    "SHOW_ASSEMBLY_FULL": ("cell_product_state", "assembly_full"),
    "SHOW_INSPECTION_FULL": ("cell_product_state", "inspection_full"),
    "CAMERA_GOOD": ("cell_product_state", "camera_good"),
    "CAMERA_DEFECT": ("cell_product_state", "camera_defect"),
    "CONVEYOR_GOOD": ("cell_conveyor_state", "good"),
    "CONVEYOR_DEFECT": ("cell_conveyor_state", "defect"),
    "R1_BOX_PLACED": ("cell_product_state", "assembly_shell"),
    "R2_PCB_PLACED": ("cell_product_state", "assembly_pcb"),
    "R3_MODULE_PLACED": ("cell_product_state", "assembly_module"),
    "R1_TERMINAL_PLACED": ("cell_product_state", "assembly_full"),
    "R3_PRODUCT_TO_INSPECTION": ("cell_product_state", "inspection_full"),
    "R4_SCREW_DONE": ("cell_screw_state", "done"),
    "R5_SORT_GOOD_DONE": ("cell_conveyor_state", "good"),
    "R5_SORT_DEFECT_DONE": ("cell_conveyor_state", "defect"),
}

# Commands accepted by Step02B_Tool_Action_Controller_V6.
TOOL_COMMANDS = {
    "R1_GRIPPER_OPEN",
    "R1_GRIPPER_CLOSE",
    "R1_GRIPPER_CLOSE_BOX",
    "R1_GRIPPER_CLOSE_TERMINAL",
    "R1_GRIPPER_CLOSE_MODULE",
    "R1_ATTACH_BOX",
    "R1_RELEASE_BOX_ASSEMBLY",
    "R1_ATTACH_MODULE",
    "R1_RELEASE_MODULE_ASSEMBLY",
    "R1_ATTACH_TERMINAL",
    "R1_RELEASE_TERMINAL_ASSEMBLY",
    "R2_VACUUM_ON",
    "R2_VACUUM_OFF",
    "R2_ATTACH_PCB",
    "R2_RELEASE_PCB_ASSEMBLY",
    "R3_GRIPPER_OPEN",
    "R3_GRIPPER_CLOSE",
    "R3_ATTACH_BOX",
    "R3_RELEASE_BOX_ASSEMBLY",
    "R3_ATTACH_ASSEMBLY_PRODUCT",
    "R3_RELEASE_PRODUCT_INSPECTION",
    "R4_SCREW_START",
    "R4_SCREW_STOP",
    "R5_GRIPPER_OPEN",
    "R5_GRIPPER_CLOSE",
    "R5_ATTACH_INSPECTION_PRODUCT",
    "R5_RELEASE_GOOD",
    "R5_RELEASE_DEFECT",
    "ALL_GRIPPERS_OPEN",
    "ALL_GRIPPERS_CLOSE",
}


def normalize_robot_id(robot_id: str) -> str:
    normalized = robot_id.strip().upper()
    if normalized not in ROBOT_ROOTS:
        raise KeyError(f"unknown robot id: {robot_id}")
    return normalized


def get_point_path(name: str) -> str:
    try:
        return POINTS[name]
    except KeyError as exc:
        raise KeyError(f"unknown target point: {name}") from exc


def get_robot_root_path(robot_id: str) -> str:
    return ROBOT_ROOTS[normalize_robot_id(robot_id)]


def get_robot_base_path(robot_id: str) -> str:
    return ROBOT_BASES[normalize_robot_id(robot_id)]


def get_home_path(robot_id: str) -> str:
    return HOME_POINTS[normalize_robot_id(robot_id)]


def get_tip_alias(robot_id: str) -> str:
    return ROBOT_TIPS[normalize_robot_id(robot_id)]


def get_joint_alias(robot_id: str, joint_num: int) -> str:
    normalize_robot_id(robot_id)
    if joint_num not in range(1, 7):
        raise ValueError(f"joint number must be 1..6, got {joint_num}")
    return ARM_JOINT_ALIASES[joint_num - 1]


def get_joint_path(robot_id: str, joint_num: int) -> str:
    """Return a path hint; clients should resolve the alias recursively."""
    normalized = normalize_robot_id(robot_id)
    return f"/{normalized}/{get_joint_alias(normalized, joint_num)}"


def resolve_object_path(name: str) -> str:
    if name.startswith("/"):
        return name
    for mapping in (
        POINTS,
        ROBOT_ROOTS,
        ROBOT_BASES,
        PARTS,
        AREAS,
        CONVEYORS,
        SENSORS,
    ):
        if name in mapping:
            return mapping[name]
    raise KeyError(f"unknown scene object name: {name}")
